### ISSUE TITLE
[feature] 오피셜 노드 상세정보 생성 기능

### ISSUE THREAD

**Issue by sanhee** [Pin-Tree/backend#48]
오피셜 노드 정보는 `서적 정보, 강의 정보, 아티클 정보`로 구성된다.

## 공통 필드

```
타입, 
제목, 
판매가,
설명, 
이미지, 
좋아요 카운트, 
바로가기 링크, 
날짜
강사/저자/글쓴이
```

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/134794251-258908e7-af4b-4b3d-b61e-def9edfa8b80.png)

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/134794898-4b9d1a83-e514-4e3b-8d37-6487298e31e6.png)

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/134815968-6df5663f-bc37-4e48-88d0-083c8068bf87.png)

구상한대로, 도메인 정의를  해보긴 했는데

abstract class를 이중으로 상속 받으면서 테이블의 타입을 구분할 수 있는 방법이 없는 것 같음..

위 설계처럼 official_node_info에 `info_type` 구분자를 만들고 싶었는데
`@DiscriminatorColumn(name = "info_type"), @DiscriminatorValue("official")` 이렇게 이중으로 쓰는건 안되는듯

```java
@Entity
@DiscriminatorColumn(name = "info_type")
@DiscriminatorValue("official")
public abstract class OfficialNodeInfo extends NodeInfo {
    String thumbnail;
    Integer wishCount;
    String shortcutUrl;
}
```


```
2021-09-27 00:54:27.191 DEBUG 22114 --- [           main] org.hibernate.SQL                        : 
    
    create table official_node_info (
       shortcut_url varchar(255),
        thumbnail varchar(255),
        wish_count integer,
        info_id bigint not null,
        primary key (info_id)
    )
```

고로...다시 설계 해봐야할 듯

**Comment by jihye-woo** [comment]
두 가지 아이디어가 떠올랐어욥👀
### 1. 중간 상속 단계를 없애기
아니면 OfficialNodeInfo, CustomNodeInfo 레벨을 없애고
LectureInfo, ArticleInfo, BookInfo, CustomInfo가 **NodeInfo를 바로 상속**하게 하는건 어떨까요?

그리고 오피셜 노드 디테일에 해당하는 LectureInfo, ArticleInfo, BookInfo는 
```java
    String thumbnail;
    Integer wishCount;
    String shortcutUrl;
```
위 세 가지 속성을 공유하니까 공통 속성들을 임베디드 타입 클래스에 묶어서 관리하구요!

![Screen Shot 2021-09-27 at 2 28 38 AM](https://user-images.githubusercontent.com/74452069/134817821-3fcf4966-54a5-4fbe-ae9c-fc4a631fd408.png)


### 2. NodeInfo는 자바에만 존재하게끔
- NodeInfo는 그냥 interface로 두어 OfficialNodeInfo와 CustomNodeInfo를 자바 코드레벨에서 하나로 묶는 용도로 사용
- 나머지는 아래와 같이 관리
![image](https://user-images.githubusercontent.com/74452069/134817658-97306305-67cb-4ff6-aff8-82d05818ceaa.png)
