### ISSUE TITLE
[bug] BookInfoRepositoryTest - Failed to load ApplicationContext

### ISSUE THREAD

**Issue by sanhee** [Pin-Tree/backend#62]
제가 하는 작업중에 BookInfoRepositoryTest 에서 엔티티를 save 하려하면, `Failed to load ApplicationContext` 에러가 발생합니다.

오늘 계속 시도해봤지만 버그가 잡히지 않아
현실적으로 예정된 일정까지 할당된 업무 완수 못할 것 같습니다..
[feature/nodeInfo-#48-error](https://github.com/Pin-Tree/backend/tree/feature/nodeInfo-%2348-error) 브랜치에 현재 제 환경 push 해두었는데, 
시간 되실 때 한번 확인해주시면 감사하겠습니다 ㅎㅎ

**Comment by jihye-woo** [comment]
LectureInfo랑 ArticleInfo가 id 값을 가지고, 또 상속받은 OfficialNodeInfo의 id 값도 가지고있어서 **PK가 두 개 선언되어있는 상태**인 것 같아요! 
그래서 subclass인 LectureInfo, ArticleInfo에 있는 id 필드를 지우면 저는 정상작동 하더라구요!

참고 : https://stackoverflow.com/a/68312949

**Comment by sanhee** [comment]
@jihye-woo 저퀄리티 질문인데 답변에 이어 해결까지 해주셔서 너무 감사합니다..!!
