### ISSUE TITLE
[feature] 다중 사용자 노드 - 노드 상세정보 엔티티 연관관계 맺기

### ISSUE THREAD

**Issue by pbg0205** [Pin-Tree/backend#68]
- [ ] 사용자 한명에 한정된 노드 - 노드 상세정보 연관관계 맺기
![image](https://user-images.githubusercontent.com/48561660/137321968-9c5440d4-cdee-47cd-8c84-4cad7536954b.png)

- [ ] 여러 사용자에 맞는 노드 - 노드 상세정보 연관관계 맺기
![image](https://user-images.githubusercontent.com/48561660/137321734-b8407726-62c3-47ad-a092-82402d815137.png)

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/137587276-208e20ac-7c2d-4c33-9441-ca41bf10bc6b.png)

**Comment by sanhee** [comment]
https://excalidraw.com/#room=13afdd678e27985c32c4,pal30FuM2aI6wjwh0HcFBg
